### ISSUE TITLE
Delay asking for access to phones files until absolutely necessary

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-android#645] opened 2019-08-20 05:32 UTC
## The Issue
When you launch the app for the first time, the first thing you see is a prompt asking to access your phone's filesystem. Can this happen later?

### Expected behaviour
I don't get the prompt until I manually trigger a file download

**Comment by tzarebczan** [comment] 2019-08-21 19:30
Duplicate of https://github.com/lbryio/lbry-android/issues/586

**Closed by tzarebczan** 2019-08-21 19:30 UTC
