### ISSUE TITLE
Sometimes you cannot play the video whiles it's downloading

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-android#126] opened 2018-05-13 22:50 UTC
## The Issue
usually you are able to play the video the moment the download starts, whereby you are able to start playing according to the percentage downloaded, but sometimes you are unable to play even though download ill be over 50%
### Steps to reproduce
1. try any random video
2. click download
3. the download progress will show on the video thumbnail and you do not get the option for play(this happens randomly, the video below happens often for me)                                                                                                                     lbry://iconoclasts-review-the-wrench-of-freedom#2b4a3ee4d865c66e6f2545a74c0f21f0ac02d0f3

### Expected behaviour
you should be able to play the video the moment the download starts

### Actual behaviour
download progress gets stuck on the video thumbnail andno option for play until download is done

## System Configuration
- Device: Samsung Note 8
- Android version: 8.0.0

## Screenshots

https://cdn.discordapp.com/attachments/439055085616496640/445194546679119872/SmartSelect_20180513-172916_LBRY_Browser.jpg

**Comment by tzarebczan** [comment] 2018-05-14 21:28
@ceoger Thanks for filing! In the case that it does not start playing immediately, does it play when the file completes? 

@akinwale I think the issue is that the same video will sometimes play immediately and other times it waits for the entire download to complete.

**Comment by akinwale** [comment] 2018-05-19 22:06
This should be fixed with https://github.com/lbryio/lbry-android/pull/131. If you still encounter the same behaviour, please feel free to reopen this issue.

**Closed by akinwale** 2018-05-19 22:06 UTC
