### ISSUE TITLE
Feature request: Add suport for Chromecast

### ISSUE THREAD

**Issue by surdu** [lbryio/lbry-android#943] opened 2020-06-23 07:29 UTC
The main reason I don't use Lbry more is because the most I consume videos in my home is on the TV. Not having Google Chromecast support is a major downside for me.

I see that [there are already efforts](https://github.com/lbryio/lbry-desktop/issues/508) on writing a Chromecast app so that the desktop app can use it, so I'm guessing adding it also to the mobile app will be somewhat straight forward.

**Comment by akinwale** [comment] 2020-06-24 09:48
Duplicate of https://github.com/lbryio/lbry-android/issues/43. There are already plans to add this feature .

**Closed by akinwale** 2020-06-24 09:48 UTC
