### ISSUE TITLE
Thumbnails seem to download all at once, consider prioritizing load sequence from top to bottom.

### ISSUE THREAD

**Issue by chamunks** [lbryio/lbry-android#106] opened 2018-05-06 19:28 UTC
### Steps to reproduce
1. Launch the app
2. Wait for media to load on Dashboard
3. Patience

### Expected behaviour
The thumbnails should likely try to prioritize which ones load first so that I'm not waiting for all of them to load even if I don't scroll down very far.  

### Actual behaviour
Tell us what happens instead

## Anything Else
Google aims to have the search result that you're going to see as the top result and tries to improve if it doesn't get you to click the top link based on your search result.  

Google Chrome also attempts to load as much of the website as possible before showing you any updates on the user interface which gives the impression that the website loads faster.  Users tend to be more frustrated having to wait for elements to load bit by bit.  It would be marginally better to show a loading element instead.

A non-trivial issue, UX specific, Improvement.

**Comment by tzarebczan** [comment] 2018-05-07 16:32
Thanks for submitting this issue!

This is a known issue in the LBRY-app as well and the root cause is a very slow client/server connection for the wallet server. The wallet server is responsible for "resolving" each URL in order to get the thumbnail and other metadata. Currently, we batch these requests all into one so not to overload the server with hundreds of requests. 

The wallet client/server re-worked mentioned in the latest development update should speed up this process, and if not, we can think of better ways to batch them so they show up quicker.

**Comment by chamunks** [comment] 2018-05-10 04:17
@tzarebczan are there relevant links that could be dumped into this issue to make the job easier in the future?

**Comment by tzarebczan** [comment] 2018-09-14 18:10
This experience should be much improved on the latest app version. Going to close this for now, but if anyone runs into something similar, please reopen.

**Closed by tzarebczan** 2018-09-14 18:10 UTC
Labels: android: open beta, area: devops, needs: exploration, type: discussion

**Comment by chamunks** [comment] 2018-09-15 19:07
Thanks @tzarebczan this was solved shortly after I posted it, within a week or so I believe unfortunately I'd not closed the ticket.
