### ISSUE TITLE
Support new metadata

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-android#500] opened 2019-03-25 18:19 UTC
Release date, tags, new creator metadata and anything else added in https://github.com/lbryio/types/pull/21

**Comment by tzarebczan** [comment] 2019-03-30 05:36
Duplicate of https://github.com/lbryio/lbry-android/issues/485 and I separated out channel metadata cause that's its own distinct effort: https://github.com/lbryio/lbry-android/issues/484

**Closed by tzarebczan** 2019-03-30 05:36 UTC
