### ISSUE TITLE
Send email doesn't trigger new verification email

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#336] opened 2018-10-10 17:22 UTC
## The Issue
If you don't confirm your email and then press the `send verification email` button (leave the rewards screen and come back if you don't see the button), nothing is sent.

**Comment by alyssaoc** [comment] 2018-11-12 19:02
couldn't reproduce, closing

**Comment by tzarebczan** [comment] 2019-04-01 16:53
I ran into this again...seems to happen if I use an email that's already existing in our system - maybe we aren't calling resend email, but just email new which 500s?  If I change the email to something like tom+2323232@lbry.com then it sends.

**Closed** 2019-05-13 18:06 UTC
Labels: type: bug
