### ISSUE TITLE
LBRYCast reward not claimed on first featured view (works on 2nd)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-android#392] opened 2019-01-09 19:22 UTC
## The Issue
The auto-claim reward function is not working after the first featured content view. You can claim it manually afterward or watch and 2nd video, and then it's claimed automatically. 

## System Configuration
- Device:
- Android version:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment] 2019-03-18 18:08
closing unable to reproduce, reopen with more detail

**Closed by alyssaoc** 2019-03-18 18:08 UTC
Labels: needs: repro, type: bug
