### ISSUE TITLE
Playback of video won't start

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-android#195] opened 2018-06-28 14:55 UTC
## The Issue
Playback won't start after download.

### Steps to reproduce
1. Go to: lbry://crypto101winklevoss-geminishadiness#ab1b0b02507e89e748edfe3439bee7832dc142d8
2. Download
3. Play

### Expected behaviour
Playback should begin

### Actual behaviour
Waited for playback to begin, but it didn't. The video window was just black, and tapping it showed this:
![screenshot_20180628-094624](https://user-images.githubusercontent.com/34570404/42041725-7a9736f6-7ac0-11e8-82a0-7bfaf8837a07.png)

## System Configuration
- Device: Huawei Nexus 6P
- Android version: 8.1.0

## Anything Else
Tried to leave and go back, tried to force close the app and reopen it, deleted the video and re-downloaded, but playback still wouldn't start.

**Comment by tzarebczan** [comment] 2018-07-03 15:22
Thanks for filing this @m160 ! @akinwale any ideas? Could it be file size?

**Comment by alyssaoc** [comment] 2018-07-23 18:57
This is related to #191 and should be merged

**Comment by akinwale** [comment] 2018-08-11 16:13
This issue turned out to be as a result of spaces (and special characters) present in the media filename. The media player expects these characters to be percent encoded in the Uri that is being set as the source. This is also the cause for https://github.com/lbryio/lbry-android/issues/213.

**Comment by akinwale** [comment] 2018-08-14 06:52
Fixed.

**Closed by akinwale** 2018-08-14 06:52 UTC
Labels: android: closed alpha, type: improvement
