### ISSUE TITLE
There is nothing happened when tapping on "LBRY Browser" notification

### ISSUE THREAD

**Issue by namujan78** [lbryio/lbry-android#307] opened 2018-09-20 03:08 UTC
## The Issue
When close/exit the LBRY android app, there is still LBRY notification. But when tapping on LBRY notification, there is nothing happened.

### Steps to reproduce
1. Open LBRY android app
2. Keep setting "" enabled
3. Open overview app and remove LBRY app
4. Show the notification
5. Tap on LBRY browser notification

### Expected behaviour
5. The LBRY should be opened

### Actual behaviour
5. There is nothing happened
Refer video in zip file:
[20180920_092312.zip](https://github.com/lbryio/lbry-android/files/2399466/20180920_092312.zip)

## System Configuration
- Device: Redme 5A
- Android version: 7.1.2
![screenshot_2018-09-20-06-44-20-734_com android settings](https://user-images.githubusercontent.com/37721875/45793446-4b6b5900-bcbc-11e8-8f29-f25983ea644e.png)

**Comment by tzarebczan** [comment] 2018-09-20 15:44
Thanks for the detailed issue! On my device (S8 plus on 8.0), I'm able to get back into the app by clicking the notification. Might be android version specific?

**Comment by alyssaoc** [comment] 2018-11-26 19:12
closing, not able to reproduce

**Comment by tzarebczan** [comment] 2018-11-26 19:19
I did run into this recently on Android 9. It seems to happen when the app is running in the background for a while. I'll give it another shot right now..

**Comment by tzarebczan** [comment] 2018-11-26 21:34
![screenshot_20181126-162635](https://user-images.githubusercontent.com/8120721/49043339-bd6a8d80-f198-11e8-9ad7-a21cd3d91bee.jpg)
In the state above, cannot click the notification to return to the app anymore, nor expand it to close. It can be swiped away only. Subsequent startup looks like a fresh start. Per my log files, it looks like the daemon just shut down abruptly - last log was a block coming in, and then nothing until the new startup.

**Comment by tzarebczan** [comment] 2019-03-02 00:17
This stopped happening to me after excluding LBRY from battery optimized apps. Worth looking into if there's a way to do this automatically or allow a user to easily whitelist.

**Comment by kauffj** [comment] 2019-10-07 18:26
@namujan78 we think we've got this one kicked, could you let us know if it happens again?

Happy to send you some LBC if you want to do some testing

**Closed by kauffj** 2019-10-07 18:26 UTC
Labels: needs: repro, product review, type: bug
